
module.exports = {
    vidLists: [
        { id: '1', category:"1", titleHsa:"Qa’idoji", titleEng: 'Instructions', uri: require('../assets/videos/upperExt/instructions.mp4'), duration: null },
        { id: '2', category:"2", titleHsa:"Tsinka Jini 1", titleEng: 'Warm Up 1', uri: require('../assets/videos/upperExt/warmUp/Warm Up 1.mp4'), duration: null },
        { id: '3', category:"2", titleHsa:"Tsinka Jini 2", titleEng: 'Warm Up 2', uri: require('../assets/videos/upperExt/warmUp/Warm Up 2.mp4'), duration: null },
        { id: '4', category:"2", titleHsa:"Tsinka Jini 3", titleEng: 'Warm Up 3', uri: require('../assets/videos/upperExt/warmUp/Warm Up 3.mp4'), duration: null },
        { id: '5', category:"2", titleHsa:"Tsinka Jini 4", titleEng: 'Warm Up 4', uri: require('../assets/videos/upperExt/warmUp/Warm Up 4.mp4'), duration: null },
        { id: '6', category:"2", titleHsa:"Tsinka Jini 5", titleEng: 'Warm Up 5', uri: require('../assets/videos/upperExt/warmUp/Warm Up 5.mp4'), duration: null },
        { id: '7', category:"3", titleHsa:"Goge kwano", titleEng: 'Cleaning Of Plate', uri: require('../assets/videos/upperExt/graspGrip/Cleaning Of Plate.mp4'), duration: null },
        { id: '8', category:"3", titleHsa:"kamawa da sakin abu", titleEng: 'Grabbing And Releasing An Object', uri: require('../assets/videos/upperExt/graspGrip/Grabbing And Releasing An Object.mp4'), duration: null },
        { id: '9', category:"3", titleHsa:"Xaga abu a bisa tebur", titleEng: 'Lifting An Object Off The Table And Changing', uri: require('../assets/videos/upperExt/graspGrip/Lifting An Object Off The Table And Changing.mp4'), duration: null },
        { id: '10', category:"3", titleHsa:"shan ruwa a kofi", titleEng: 'Lifting Cup Of Water To The Mouth', uri: require('../assets/videos/upperExt/graspGrip/Lifting Cup Of Water To The Mouth.mp4'), duration: null },
        { id: '11', category:"3", titleHsa:"Sauke abu daga bisa tebur zuwa qasa", titleEng: 'Lifting Object From Table To The Ground', uri: require('../assets/videos/upperExt/graspGrip/Lifting Object From Table To The Ground.mp4'), duration: null },
        { id: '12', category:"3", titleHsa:"Buxe murfin kwano", titleEng: 'Opening The Cover Of Eating Bowl', uri: require('../assets/videos/upperExt/graspGrip/Opening The Cover Of Eating Bowl.mp4'), duration: null },
        { id: '13', category:"3", titleHsa:"Buxe murfin roba", titleEng: 'Taking Off The Lid Of A Jar', uri: require('../assets/videos/upperExt/graspGrip/Taking Off The Lid Of A Jar.mp4'), duration: null },
        { id: '14', category:"3", titleHsa:"kama abu da ke sama", titleEng: 'Touching And Holding Object Above Infront', uri: require('../assets/videos/upperExt/graspGrip/Touching And Holding Object Above Infront.mp4'), duration: null },
        { id: '15', category:"4", titleHsa:"Alwala", titleEng: 'Ablution', uri: require('../assets/videos/upperExt/handNFinger/Ablution.mp4'), duration: null },
        { id: '16', category:"4", titleHsa:"Valle mavallin riga", titleEng: 'Bottoning Shirt', uri: require('../assets/videos/upperExt/handNFinger/Bottoning Shirt.mp4'), duration: null },
        { id: '17', category:"4", titleHsa:"Vare abu mai kwanso", titleEng: 'Breaking Pea Nut', uri: require('../assets/videos/upperExt/handNFinger/Breaking Pea Nut.mp4'), duration: null },
        { id: '18', category:"4", titleHsa:"Qyasta ashana", titleEng: 'Igniting Match Stick', uri: require('../assets/videos/upperExt/handNFinger/Igniting Match Stick.mp4'), duration: null },
        { id: '19', category:"4", titleHsa:"Danna lambobi a waya", titleEng: 'Pressing Phone Keyboard', uri: require('../assets/videos/upperExt/handNFinger/Pressing Phone Keyboard.mp4'), duration: null },
        { id: '20', category:"5", titleHsa:"Buxe maqulli", titleEng: 'Opening Padlock With Key', uri: require('../assets/videos/upperExt/objectManipulation/Opening Padlock With Key.mp4'), duration: null },
        { id: '21', category:"5", titleHsa:"Buxe roba mai murfi", titleEng: 'Opening Jar With Lid', uri: require('../assets/videos/upperExt/objectManipulation/Opening Jar With Lid.mp4'), duration: null },
        { id: '22', category:"5", titleHsa:"Buxe qofa da maqulli", titleEng: 'Opening The Door With Key', uri: require('../assets/videos/upperExt/objectManipulation/Opening The Door With Key.mp4'), duration: null },
        { id: '23', category:"5", titleHsa:"Cire kuxi daga aljihu", titleEng: 'Picking Money Out Of Pocket', uri: require('../assets/videos/upperExt/objectManipulation/Picking Money Out Of Pocket.mp4'), duration: null },
        { id: '24', category:"5", titleHsa:"Zuba ruwa cikin kof", titleEng: 'Pouring Water From A Jar In To A Cup', uri: require('../assets/videos/upperExt/objectManipulation/Pouring Water From A Jar In To A Cup.mp4'), duration: null },
        { id: '25', category:"5", titleHsa:"Wankin kaya", titleEng: 'Training For Washing', uri: require('../assets/videos/upperExt/objectManipulation/Training For Washing.mp4'), duration: null },
        { id: '26', category:"5", titleHsa:"Xiban gari daga cikin roba", titleEng: 'Transfer Of Powdered Substance From A Jar', uri: require('../assets/videos/upperExt/objectManipulation/Transfer Of Powdered Substance From A Jar.mp4'), duration: null },
        { id: '27', category:"5", titleHsa:"Ninke tufa", titleEng: 'Unfolding And Folding A Cloth', uri: require('../assets/videos/upperExt/objectManipulation/Unfolding And Folding A Cloth.mp4'), duration: null },
        { id: '28', category:"5", titleHsa:"Saka hula", titleEng: 'Wearing A Cap', uri: require('../assets/videos/upperExt/objectManipulation/Wearing A Cap.mp4'), duration: null },
        { id: '29', category:"5", titleHsa:"Xaura xankwali", titleEng: 'Wearing A Head Tie', uri: require('../assets/videos/upperExt/objectManipulation/Wearing A Head Tie.mp4'), duration: null },
        { id: '30', category:"5", titleHsa:"Tsince qwaya", titleEng: 'With Affected Hand Pick Tiger Nuts From Plate', uri: require('../assets/videos/upperExt/objectManipulation/With Affected Hand Pick Tiger Nuts From Pe.mp4'), duration: null },
        { id: '31', category:"5", titleHsa:"Xaura zani", titleEng: 'With Both Hands Tie Wrapper Around Your Waist', uri: require('../assets/videos/upperExt/objectManipulation/With Both Hands Tie Wrapper Around Your Waist.mp4'), duration: null },
        { id: '32', category:"6", titleHsa:"Tava abu akan tebur", titleEng: 'Reaching An Object On A Table', uri: require('../assets/videos/upperExt/reaching/Reaching An Object On A Table.mp4'), duration: null },
        { id: '33', category:"6", titleHsa:"Tava  abu a sama a gaba", titleEng: 'Reaching Object Placed Above In front', uri: require('../assets/videos/upperExt/reaching/Reaching Object Placed Above Infront.mp4'), duration: null },
        { id: '34', category:"6", titleHsa:"sosa kai", titleEng: 'Touching And Scratching The Head', uri: require('../assets/videos/upperExt/reaching/Touching And Scratching The Head.mp4'), duration: null },
        { id: '35', category:"6", titleHsa:"Tava kafaxu", titleEng: 'Touching Both Shoulders At Once', uri: require('../assets/videos/upperExt/reaching/Touching Both Shoulders At Once.mp4'), duration: null },
    ],
    categories:[
        {id:'1' , nameHsa:'Qa’idoji', nameEng:'Instructions'},
        {id:'2' , nameHsa:'Tsinka Jini', nameEng:'Warm up'},     
        {id:'3' , nameHsa:'Ayyuka don koyon rikewa/motsa abubuwa', nameEng:'Training for grasp/grip and moving objects'},     
        {id:'4' , nameHsa:'Ayukan inganta lafiyar hannu da ‘yan yatsu', nameEng:'Training for hand and fingers precision'},     
        {id:'5' , nameHsa:'Horo wajen sarrafa abubuwa', nameEng:'Training for object manipulations'},     
        {id:'6' , nameHsa:'Ayyuka don cimma abu', nameEng:'Training for reaching'},     
        
    ]
}